### ISSUE TITLE
error :Message: Birth year is out ff 1900-2100 range for new NIC

### ISSUE THREAD

**Issue by nuwaninfo** [slwdc/NICParser#1]
Hi Ayesh,

First of all thank you very much for sharing this. But it gives an error when tested with sample new nic given by you('199226025738'). Appreciate if you could look into this.

An uncaught Exception was encountered
Type: SLWDC\NICParser\Exception\InvalidArgumentException

Message: Birth year is out ff 1900-2100 range

Filename: .....\vendor\slwdc\nic-parser\src\Parser.php

Line Number: 73

**Comment by Ayesh** [comment]
Thanks for the report. 
I will take a look late today and improve the tests. Admittedly it's been some time since I touched this. 

As always, PRs are welcome.

**Comment by nuwaninfo** [comment]
Dear Ayesh,

Thank you for the quick reply. I think error occurred when parsing nic which is in String to Integer.

when parse "199226025738" to int it gives wrong value. It will work as follows.

(float) '199226025738'

Anyway thank you for the nice script.

**Comment by Ayesh** [comment]
Hi @nuwaninfo - I have done some tests and improved test coverage. I think the problem is that you are using a 32-bit processor that overflows an int like 199226025738. PHP silently overflows them (signed 32 bit integers), so the ID card number the plugin sees is invalid. 

Because the majority of systems support 64-bit nowadays, I don't think it's a good idea to use BCMath or such workarounds for 32 bit systems. I suppose the ideal solution is that you upgrade your system to 64-bit.
